# Config docs: https://gohugo.io/overview/configuration/

baseurl = "/"
languageCode = "en-us"
title = "Northland Church Demo"

# Do not inject generator meta tag on homepage.
disableHugoGeneratorInject = true
metaDataFormat = "yaml"

[taxonomies]
eventtype = "eventtypes"

[permalinks]
events = "calendar/:section/:year/:month/:day/:title"


# Define to add Google Analytics to the page. ( UA-XXXXX-X )
# https://gohugo.io/extras/analytics/
googleAnalytics = ""

# Define to add Disqus Comments.
# https://gohugo.io/extras/comments/
disqusShortname = ""