# Based on: https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md
backend:
  name: github
  repo: smakinson/northlandchurch-demo
  branch: master

publish_mode: editorial_workflow
media_folder: "site/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "event"
    label: "Event"
    folder: "site/content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: "Title", name: "title", widget: "string", default: "" }
       - { label: "Event Type", name: "event-type", widget: "string", default: "" }
       - { label: "Main Image", name: "main-image", widget: "image", default: "" }
       - { label: "Event Type", name: "event-type", widget: "string", default: "" }
       - { label: "Start Date", name: "start-date", widget: "datetime", default: "" }
       - { label: "Audience", name: "audience", widget: "string", default: "" }
       - { label: "Cost", name: "cost", widget: "string", default: "Free" }
       - { label: "Description", name: "description", widget: "markdown", default: "" }
  - name: "event-type"
    label: "Event Type"
    folder: "site/content/event-types"
    create: true
    slug: "{{slug}}"
    fields:
       - { label: "Title", name: "title", widget: "string", default: "" }


#- { label: "", name: "", widget: "", default: "" }